# Copy this configuration file into your Jekyll site's root directory.
url: "https://10deploys.com"
title: 10deploys theme
language: en
timezone: America/Sao_Paulo
description: The theme of the 10deploys website.
twitter_username: "@10deploys"

exclude:
  - docker-compose.yml
  - LICENSE.txt
  - Gemfile
  - Gemfile.lock
  - README.md

# sass:
#   style: compressed

# theme: 10deploys-theme

plugins:
  - jekyll-paginate-v2

# See: https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#page-configuration
pagination:
  enabled: true
  debug: false

collections:
  pages:
    output: true
    permalink: /pages/:title
  episodes:
    output: true
    permalink: /episodes/:title

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      image: ~
      description: ~
      toc: ~
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode
      image: ~
      number: ~
      recording: ~
      toc: ~
      guests: ~
      references: ~
      recommendations: ~
      media_credits: ~
  - scope:
      path: assets/defaults
    values:
      image: true
  - scope:
      path: assets/episodes
    values:
      image: true
  - scope:
      path: assets/pages
    values:
      image: true

defaults_assets_path: /assets/defaults
episodes_assets_path: /assets/episodes
pages_assets_path: /assets/pages
cover_filename: cover.jpg
cover_medium_filename: cover-medium.jpg
cover_small_filename: cover-small.jpg
